#OUTCOME/DEPENDENT VARIABLE(Y)=LENGTH OF STAY IN HOSPITAL
#X1 = INDEPENDENT VARIABLE(X1)=SMOKE(YES/NO)
#X2=INDEPENDENT VARIABLE= ASBESTOS EXPOSURE(NO/YES)

#INTERACTION=THE EFFECT OF ASBESTOS  EXPOSTURE ON LENGTH OF STAY IS DEPENDENT ON SMOKING
# AND THE EFFECT OF SMOKING ON LENGTH OF STAY IS DEPENDENT ON ASBESTOS EXPOSURE
#LINEAR REGRESSION EQUATION= b0+b1*smoke+b2*asbestos+b12*smoke*age